services:
  # バックエンド (FastAPI)
  backend:
    build: 
      context: ${PROJECT_ROOT}/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ENVIRONMENT=development
      - FRONTEND_NGROK_URL=${FRONTEND_NGROK_URL}
      - BACKEND_NGROK_URL=${BACKEND_NGROK_URL}
      - PYTHONPATH=/app
      - APP_ROOT=/app
    volumes:
      - ${PROJECT_ROOT}/backend:/app
      - ${PROJECT_ROOT}/backend/db:/app/db
      - ${PROJECT_ROOT}/conf/.env:/app/.env # .envを明示的にマウント
    networks:
      - app-network
    restart: unless-stopped

  # ngrok (複数トンネル) - backendの後に起動
  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: >
      start --authtoken ${NGROK_AUTHTOKEN} 
      --config /etc/ngrok.yml 
      frontend backend
    volumes:
      - type: bind
        source: ${PROJECT_ROOT}/conf/ngrok.yml
        target: /etc/ngrok.yml
        read_only: true
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  # フロントエンド (Next.js) - ngrokの後に起動
  frontend:
    build:
      context: ${PROJECT_ROOT}/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_BACKEND_NGROK_URL: ${NEXT_PUBLIC_BACKEND_NGROK_URL}
        NEXT_PUBLIC_FRONTEND_NGROK_URL: ${NEXT_PUBLIC_FRONTEND_NGROK_URL}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_BACKEND_NGROK_URL=${NEXT_PUBLIC_BACKEND_NGROK_URL}
      - NEXT_PUBLIC_FRONTEND_NGROK_URL=${NEXT_PUBLIC_FRONTEND_NGROK_URL}
    volumes:
      - ${PROJECT_ROOT}/conf/.env:/app/.env
    networks:
      - app-network
    depends_on:
      - ngrok
    restart: unless-stopped

  # 環境変数更新サービス
  env-updater:
    image: curlimages/curl:latest
    volumes:
      - ${PROJECT_ROOT}/conf/update-env.sh:/update-env.sh
      - ${PROJECT_ROOT}/conf/.env:/.env
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: >
      sh -c "
        chmod +x /update-env.sh &&
        sleep 10 &&
        /update-env.sh
      "
    networks:
      - app-network
    depends_on:
      - ngrok
    restart: "no"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge