name: Terraform Deploy

on:
  pull_request:
    paths:
      - 'terraform/**'
  push:
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Format
        run: terraform -chdir=terraform fmt -check
      - name: Terraform Validate
        run: terraform -chdir=terraform validate
      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Apply (manual approval required)
        run: |
          echo "Manual approval required to apply Terraform to production."
          echo "Set RENDER_API_KEY secret in repository settings and re-run this job after approval."
        # For safety, we don't auto-apply in this skeleton. Operators can uncomment apply steps below.
        # - run: terraform -chdir=terraform apply -auto-approve
